name: clean_arch_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  # Charts
  fl_chart: ^1.1.1
  # PDF & Export
  pdf: ^3.11.3
  printing: ^5.14.2
  # Date & Time
  intl: ^0.20.2
  # Icons
  font_awesome_flutter: ^10.12.0
  # Web download
  universal_html: ^2.2.4
  # Persistence
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
